name: Waves Effect
on:
  workflow_dispatch:
  push:
permissions:
  contents: write
  packages: write
  checks: write
  pull-requests: write

jobs:
  WavesEffect:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: ''
      name: 'Waves Effect'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}

